//Copyright (C)2014-2025 Gowin Semiconductor Corporation.
//All rights reserved.
//File Title: Template file for instantiation
//Tool Version: V1.9.11.01 (64-bit)
//Part Number: GW2A-LV18PG256C8/I7
//Device: GW2A-18
//Device Version: C
//Created Time: Thu May  8 21:44:07 2025

//Change the instance name and port connections to the signal names
//--------Copy here to design--------

	Gowin_AHB_Arbiter_Top your_instance_name(
		.HCLK(HCLK), //input HCLK
		.HRESETn(HRESETn), //input HRESETn
		.MHSELS0(MHSELS0), //input MHSELS0
		.MHADDRS0(MHADDRS0), //input [31:0] MHADDRS0
		.MHTRANSS0(MHTRANSS0), //input [1:0] MHTRANSS0
		.MHWRITES0(MHWRITES0), //input MHWRITES0
		.MHSIZES0(MHSIZES0), //input [2:0] MHSIZES0
		.MHBURSTS0(MHBURSTS0), //input [2:0] MHBURSTS0
		.MHPROTS0(MHPROTS0), //input [3:0] MHPROTS0
		.MHMASTERS0(MHMASTERS0), //input [3:0] MHMASTERS0
		.MHWDATAS0(MHWDATAS0), //input [31:0] MHWDATAS0
		.MHMASTLOCKS0(MHMASTLOCKS0), //input MHMASTLOCKS0
		.MHREADYS0(MHREADYS0), //input MHREADYS0
		.MHRDATAS0(MHRDATAS0), //output [31:0] MHRDATAS0
		.MHREADYOUTS0(MHREADYOUTS0), //output MHREADYOUTS0
		.MHRESPS0(MHRESPS0), //output [1:0] MHRESPS0
		.MHSELS1(MHSELS1), //input MHSELS1
		.MHADDRS1(MHADDRS1), //input [31:0] MHADDRS1
		.MHTRANSS1(MHTRANSS1), //input [1:0] MHTRANSS1
		.MHWRITES1(MHWRITES1), //input MHWRITES1
		.MHSIZES1(MHSIZES1), //input [2:0] MHSIZES1
		.MHBURSTS1(MHBURSTS1), //input [2:0] MHBURSTS1
		.MHPROTS1(MHPROTS1), //input [3:0] MHPROTS1
		.MHMASTERS1(MHMASTERS1), //input [3:0] MHMASTERS1
		.MHWDATAS1(MHWDATAS1), //input [31:0] MHWDATAS1
		.MHMASTLOCKS1(MHMASTLOCKS1), //input MHMASTLOCKS1
		.MHREADYS1(MHREADYS1), //input MHREADYS1
		.MHRDATAS1(MHRDATAS1), //output [31:0] MHRDATAS1
		.MHREADYOUTS1(MHREADYOUTS1), //output MHREADYOUTS1
		.MHRESPS1(MHRESPS1), //output [1:0] MHRESPS1
		.SHRDATAM0(SHRDATAM0), //input [31:0] SHRDATAM0
		.SHREADYOUTM0(SHREADYOUTM0), //input SHREADYOUTM0
		.SHRESPM0(SHRESPM0), //input [1:0] SHRESPM0
		.SHSELM0(SHSELM0), //output SHSELM0
		.SHADDRM0(SHADDRM0), //output [31:0] SHADDRM0
		.SHTRANSM0(SHTRANSM0), //output [1:0] SHTRANSM0
		.SHWRITEM0(SHWRITEM0), //output SHWRITEM0
		.SHSIZEM0(SHSIZEM0), //output [2:0] SHSIZEM0
		.SHBURSTM0(SHBURSTM0), //output [2:0] SHBURSTM0
		.SHPROTM0(SHPROTM0), //output [3:0] SHPROTM0
		.SHMASTERM0(SHMASTERM0), //output [3:0] SHMASTERM0
		.SHWDATAM0(SHWDATAM0), //output [31:0] SHWDATAM0
		.SHMASTLOCKM0(SHMASTLOCKM0), //output SHMASTLOCKM0
		.SHREADYMUXM0(SHREADYMUXM0) //output SHREADYMUXM0
	);

//--------Copy end-------------------
